export const CONSTANTS = {
  BCRYPT_ROUNDS: 12,
  MAX_FAILED_LOGINS: 5,
  LOCK_DURATION_MINUTES: 30,
  REFRESH_TOKEN_FAMILY_LIMIT: 10,
  DEFAULT_PAGE_SIZE: 10,
  MAX_PAGE_SIZE: 100,
  API_PREFIX: '/api/v1',
} as const;
